.onLoad <- function(lib, pkg) {
  Sys.setenv(TZ = "GMT")
  Sys.setenv(RspecroAbs_DATA_DIR=paste(lib, pkg, "data", sep="/"))
  cat("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n")
  cat("This package provides facilities to process particulate and CDOM absorption spectra\n")
  cat("Prior running the code, you need to prepare the data and put the list\n")
  cat("of samples to process in an ASCII file. \n")
  cat("\n")
  cat("THE PROCESSING OF Particulate absorption proceed in 3 steps:, \n")
  cat("1.  Conversion from OD to absorption coefficient in /m with run.process.Ap.batch()\n")
  cat("2.  Average the replicates run.process.replicate.batch()\n")
  cat("3.  Compute phytoplankton absorption with run.compute.Aph.batch()\n")
  cat("\n")
  cat("THE PROCESSING OF CDOM absorption (Ag) proceed in only one step:, \n")
  cat("1.  Conversion from OD to absorption coefficient in /m with run.process.Ag.batch()\n")
  cat("\n")
  cat("In both case, a data base can be generate using generate.Ag.BD()\n")
  cat("or generate.Ap.BD()")
  cat("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n")
}
